### ISSUE TITLE
Value matching in UTags is looking for substrings, not exact matches

### ISSUE THREAD

**Issue by Sanic** [robcog-iai/UUtils#12]
Hi,

is it expected that when looking for values in Key/Value pairs with UTags that values are not matched exactly, but rather by looking if the given value is a substring of the existing values?
This might arise from here:
https://github.com/robcog-iai/UUtils/blob/master/Source/UTags/Private/Tags.cpp#L191

The situation i encountered today was that i had two actors with Semlog IDs 'abcOLD' and 'abc'.
While trying to change the pose of the object "abc" with UROSWorldControl the pose of abcOLD oinstead of abc got changed. That was a little bit counterintuitive to me.

What do you think?

**Comment by andreihaidu** [comment]
Hi

changing the code to, should fix the issue:

`return InTag.ToString().Find(";" + TagKey + "," + TagValue + ";") != INDEX_NONE;`
